#' Randomly generated y for linear regression modeling
#'
#' A dataset containing the randomly generated y.
#'
#' @format A 1-D numeric vector with 10000 rows generated by multiplying x with randomly generated betas from the normal distribution with mean = 1 and sd = 10, then adding errors randomly generated from the normal distribution with mean = 0 and sd = 0.5:
#'
#'
"y"
